// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDspXJmSQNy4UEg75rk0pYP_iDg4Fq7T5o',
    appId: '1:770487128361:android:8e81163302f80f80146738',
    messagingSenderId: '770487128361',
    projectId: 'digimartshop',
    storageBucket: 'digimartshop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD47RMR7A_wpKh230md-jM17QH5Msbd7g',
    appId: '1:770487128361:ios:d17e43a744b1b5fb146738',
    messagingSenderId: '770487128361',
    projectId: 'digimartshop',
    storageBucket: 'digimartshop.appspot.com',
    androidClientId: '770487128361-tc0fj8oir8h9j3tbeifk2hq5srr7lgeq.apps.googleusercontent.com',
    iosClientId: '770487128361-902tlp67a6lg06b0qa73gi7q45tkilu2.apps.googleusercontent.com',
    iosBundleId: 'hn.digimartbox.digimartbox',
  );
}
